# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/myfolder/YAZIS/NLP_App/view/templates/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, form=None) -> None:
        self.setupUi(form)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.raw_text_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.raw_text_textEdit.setGeometry(QtCore.QRect(20, 30, 671, 241))
        self.raw_text_textEdit.setObjectName("raw_text_textEdit")
        self.raw_text_label = QtWidgets.QLabel(self.centralwidget)
        self.raw_text_label.setGeometry(QtCore.QRect(300, 10, 81, 16))
        self.raw_text_label.setObjectName("raw_text_label")
        self.output_text_label = QtWidgets.QLabel(self.centralwidget)
        self.output_text_label.setGeometry(QtCore.QRect(290, 340, 101, 16))
        self.output_text_label.setObjectName("output_text_label")
        self.output_text_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text_textEdit.setGeometry(QtCore.QRect(20, 360, 671, 201))
        self.output_text_textEdit.setObjectName("output_text_textEdit")
        self.send_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.send_pushButton.setGeometry(QtCore.QRect(290, 280, 89, 25))
        self.send_pushButton.setObjectName("send_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_Doc = QtWidgets.QAction(MainWindow)
        self.actionOpen_Doc.setObjectName("actionOpen_Doc")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.raw_text_label.setText(_translate("MainWindow", "YOUR TEXT"))
        self.output_text_label.setText(_translate("MainWindow", "OUTPUT TEXT"))
        self.send_pushButton.setText(_translate("MainWindow", "SEND"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionOpen_Doc.setText(_translate("MainWindow", "Open Doc..."))
