# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/myfolder/YAZIS/NLP_App/view/templates/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, form=None) -> None:
        self.setupUi(form)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 220, 671, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.add_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.add_pushButton.setGeometry(QtCore.QRect(100, 510, 75, 23))
        self.add_pushButton.setObjectName("add_pushButton")
        self.process_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.process_pushButton.setGeometry(QtCore.QRect(20, 510, 75, 23))
        self.process_pushButton.setObjectName("process_pushButton")
        self.raw_text_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.raw_text_textEdit.setGeometry(QtCore.QRect(20, 30, 671, 161))
        self.raw_text_textEdit.setObjectName("raw_text_textEdit")
        self.raw_text_label = QtWidgets.QLabel(self.centralwidget)
        self.raw_text_label.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.raw_text_label.setObjectName("raw_text_label")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(20, 200, 61, 16))
        self.result_label.setObjectName("result_label")
        self.filter_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.filter_pushButton.setGeometry(QtCore.QRect(300, 510, 75, 21))
        self.filter_pushButton.setObjectName("filter_pushButton")
        self.filter_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.filter_textEdit.setGeometry(QtCore.QRect(390, 520, 301, 31))
        self.filter_textEdit.setObjectName("filter_textEdit")
        self.delete_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.delete_pushButton.setGeometry(QtCore.QRect(180, 510, 75, 23))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.reset_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reset_pushButton.setGeometry(QtCore.QRect(300, 540, 75, 21))
        self.reset_pushButton.setObjectName("reset_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_Doc = QtWidgets.QAction(MainWindow)
        self.actionOpen_Doc.setObjectName("actionOpen_Doc")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Doc)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "LEXEM/WORDFORM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SEENUMBER"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NOTES"))
        self.add_pushButton.setText(_translate("MainWindow", "ADD"))
        self.process_pushButton.setText(_translate("MainWindow", "PROCESS"))
        self.raw_text_label.setText(_translate("MainWindow", "RAW TEXT"))
        self.result_label.setText(_translate("MainWindow", "RESULT"))
        self.filter_pushButton.setText(_translate("MainWindow", "FILTER"))
        self.delete_pushButton.setText(_translate("MainWindow", "DELETE"))
        self.reset_pushButton.setText(_translate("MainWindow", "RESET"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionOpen_Doc.setText(_translate("MainWindow", "Open Doc..."))
